### ISSUE TITLE
public 폴더에 있는 image 출력이 되지 않음

### ISSUE THREAD

**Issue by otterbits** [nerd-animals/na-log#23]
### 관련 업데이트

#21

### 버그 설명

public 폴더에 있는 profile 사진을 bio에 추가하려고 했는데, 정상적으로 출력하지 않습니다.

### 버그 발생 방식

1. public 폴더에 profile 사진을 추가하고, 
2. bio에서 <Image>태그를 이용하여 출력했더니
3. 
![image](https://github.com/nerd-animals/na-log/assets/144116866/697167d4-d7c3-4840-bb38-bd974f31937a)
이미지가 제대로 출력되지 않습니다.

### 예상 응답(선택)

이미지를 찾지 못하는 것이 아닌, 제대로 찾아서 출력해줘야합니다.

### Browsers(선택)

Chrome

### OS(선택)

Mac

**Comment by otterbits** [comment]
``output: export`` 는 모든 페이지들이 사전 빌드되는 옵션입니다.
하지만 ``Image`` 태그는 서버에서 최적화를 시켜 내보내는데, 사전 빌드가 된다면 서버 랜더링이 필요없기 때문에 오류가 뜨는 것으로 생각됩니다.

밑의 ``unoptimized: true``로 최적화를 시키지 않고 원본 그대로 내보낸다면, 사전 빌드되도 public 폴더에서 제대로 출력이 됩니다.
하지만, Image 태그의 이점을 살리지 못하기 때문에 좋은 방안은 아닌 것 같습니다.

**Comment by SanGyuk-Raccoon** [comment]
'Image 태그의 최적화'와 'SSG'에 대해 한번 고민해볼 필요가 있습니다.

[링크](https://oliveyoung.tech/blog/2023-06-09/nextjs-image-optimization/) 아래의 요약 중, 이런 문장이 있습니다.
> 이미지 최적화는 빌드 타임이 아닌 런타임에 요청이 들어왔을 때 최적화를 진행한다. 그렇기에 최초 1회 요청은 응답이 느릴 수 있다.

즉, 서버로 요청이 들어왔을 때, Image태그에 의한 최적화의 이점을 받을 수 있다는 뜻으로 보입니다.
이는 SSR 방식인 것으로 예상됩니다.

우리는 SSG 방식으로 배포하므로, 관련 사이트들이 모두 정적으로 생성되어 있습니다.
그렇다면, 서버에 요청이 들어왔을 때, 최적화를 할 것이 있을까요?

> output: export 는 모든 페이지들이 사전 빌드되는 옵션입니다.
> 하지만 Image 태그는 서버에서 최적화를 시켜 내보내는데, 사전 빌드가 된다면 서버 랜더링이 필요없기 때문에 오류가 뜨는 것으로 생각됩니다.

정확한 확인은 필요합니다만, 이미 위에서 정답을 찾은 것은 아니었을까 싶습니다 😂

**Comment by SanGyuk-Raccoon** [comment]
아래는 제 의견입니다.

SSG는, 미리 모든 페이지를 생성해놓습니다.
SSR은, 서버에 요청했을 때 서버가 페이지를 생성해서 제공합니다.

SSG는 전통적인 배포 방식으로, 제약사항이 많은 방식입니다. 대신 그만큼 빠르죠!
SSR은 서버에서 페이지를 생성하므로, 페이지 변경에 있어서 SSG보다 유리합니다. 그 과정에서 Image의 최적화가 끼일 여지가 있죠.

우리는 SSG라는 제약사항이 있는 배포방식을 택한 대신, 
최적화가 필요없는 가장 빠른 배포 방법을 선택한 것이 아닐까요?

**Comment by SanGyuk-Raccoon** [comment]
`최적화`라는 단어에 현혹되지 말고, 정확한 동작원리를 파악하는 것이 필요합니다.
