### ISSUE TITLE
about page에 사진 추가

### ISSUE THREAD

**Issue by otterbits** [nerd-animals/na-log#27]
### 기능 설명

Intro, about, project에 관련 사진이 없어 완성도 면에서 부족합니다.
#23 이 해결되는 대로 추가합니다.

### 참고 자료(선택)

![image](https://github.com/nerd-animals/na-log/assets/144116866/1e871bb8-efb0-4107-999a-2b0201dfd0be)

Na-log 및 todo-list 예시 디자인은 작업이 진행되는 대로 추가하겠습니다.

**Comment by SanGyuk-Raccoon** [comment]
about 정책에 따라 처리가 필요없는 이슈입니다.
