### ISSUE TITLE
Frontmatter 항목

### ISSUE THREAD

**Issue by SanGyuk-Raccoon** [nerd-animals/na-log#34]
### 기능 설명

frontmatter에 뭐가 들어가야할까요?

**Comment by SanGyuk-Raccoon** [comment]
| 항목 | type | required |
| --- | --- | --- |
| title | string | True |

**Comment by otterbits** [comment]
항목 | type | required
-- | -- | --
title | string | True
summary | string | true
date | string | True
author | string | True
categories | string | True

**Comment by SanGyuk-Raccoon** [comment]
항목 | type | required
-- | -- | --
title | string | True
summary | string | True
date | date | True
author | string | True
tags | list | False
categories | list | True(후처리에서 관리. 폴더 구조 차용)

**Comment by otterbits** [comment]
categories 미추가로 오픈합니다.
